plugins {
    id 'net.fabricmc.fabric-loom'
}

loom {
    // accessWidenerPath = project(":common").file("src/main/resources/sdrp.accesswidener")

    runs {
        configureEach {
            ideConfigGenerated = true
        }
    }

    mods {
        "sdrp" {
            sourceSet sourceSets.main
            sourceSet("main", ":common")
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    implementation("dev.nanite.mods:nanite-library-fabric:${nanite_library_version}")
    include(api("dev.nanite.forks:discord-ipc:${ipc_version}"))
}

java {
    withSourcesJar()
}
