plugins {
    id 'java-library'
    id 'fabric-loom' version '1.15-SNAPSHOT' apply(false)
    id 'net.neoforged.moddev' version '2.0.141' apply(false)
    id "me.modmuss50.mod-publish-plugin" version "1.1.0"
}

def ENV = System.getenv()

allprojects {
    apply plugin: 'idea'
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'

    version = "${mod_version}-build.${ENV.GITHUB_RUN_NUMBER ?: 9999}+mc${minecraft_version}"
    group = maven_group

    repositories {
        mavenLocal()
        maven {
            url = "https://jitpack.io"
            content {
                includeGroup "com.github.rtyley"
                includeGroup "com.github.jagrosh"
            }
        }
        maven {
            url = "https://maven.latvian.dev/releases"
            content {
                includeGroup "dev.latvian.mods"
                includeGroup "dev.latvian.apps"
            }
        }
        maven {
            url "https://maven.nanite.dev/releases"
            content {
                includeGroup "dev.nanite.forks"
            }
        }
        maven {
            url = "https://maven.shedaniel.me/"
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 25
    }

    idea {
        module {
            downloadSources = true
            downloadJavadoc = true
        }
    }
}

subprojects {
    base {
        archivesName = rootProject.archives_base_name + project.name
    }

    if (project.name != "common") {
        dependencies {
            api project(":common")
        }

        jar {
            from project(":common").sourceSets.main.output
        }
    }

    def replaceProperties = [
            mod_id: mod_id,
            minecraft_version: minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neoforge_version: neoforge_version,
            neoforge_version_range: neoforge_version_range,
            fabric_loader_version: fabric_loader_version,
            fabric_api_version: fabric_api_version,
            cloth_config_version: cloth_config_version,
            cloth_config_version_range: cloth_config_version_range,
            version: version,
    ]

    processResources {
        inputs.properties replaceProperties

        filesMatching(["META-INF/neoforge.mods.toml", "fabric.mod.json"]) {
            expand replaceProperties
        }
    }

    publishing {
        publications {
            register("maven${project.name.capitalize()}", MavenPublication) {
                artifactId = "${rootProject.archives_base_name}-${project.name}"
                from components.java
            }
        }

        repositories {
            def token = providers.environmentVariable("NANITE_TOKEN");
            if (token.isPresent()) {
                maven {
                    url "https://maven.nanite.dev/releases"
                    credentials {
                        username = "nanite"
                        password = providers.environmentVariable("NANITE_TOKEN").get()
                    }
                }
            }
        }
    }
}

publishMods {
    dryRun = providers.environmentVariable("CURSE_TOKEN").getOrNull() == null
    changelog = file("./CHANGELOG.md").text
    version = "${mod_version}"
    type = STABLE

    def fabricOptions = publishOptions {
        file = project.provider { project(":fabric").tasks.jar }.flatMap { it.archiveFile }
        displayName = "[FABRIC][${minecraft_version}] ${project.name} ${mod_version}"
        modLoaders.add("fabric")
    }

    def neoforgeOptions = publishOptions {
        file = project.provider { project(":neoforge").tasks.jar }.flatMap { it.archiveFile }
        displayName = "[NEOFORGE][${minecraft_version}] ${project.name} ${mod_version}"
        modLoaders.add("neoforge")
    }

    def curseForgeOptions = curseforgeOptions {
        accessToken = providers.environmentVariable("CURSE_TOKEN")
        projectId = "${curseforge_id}"
        minecraftVersions.add("${minecraft_version}")
    }

    def modrinthOptions = modrinthOptions {
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        projectId = "${modrinth_id}"
        minecraftVersions.add("${minecraft_version}")
    }

    curseforge("curseforgeFabric") {
        from(curseForgeOptions, fabricOptions)
        requires("fabric-api")
        requires("cloth-config")
    }

    curseforge("curseforgeNeoforge") {
        from(curseForgeOptions, neoforgeOptions)
        requires("cloth-config")
    }

    if (providers.environmentVariable("MODRINTH_TOKEN").getOrNull() != null) {
        modrinth("modrinthFabric") {
            from(modrinthOptions, fabricOptions)
            requires("fabric-api")
            requires("cloth-config")
        }

        modrinth("modrinthNeoforge") {
            from(modrinthOptions, neoforgeOptions)
            requires("cloth-config")
        }
    }
}
