org.gradle.jvmargs=-Xmx3G

mod_id=sdrp
archives_base_name=SimpleDiscordRichPresence
mod_version=99.0.0
maven_group=com.sunekaer.mods

curseforge_id=334853
modrinth_id=SCAopByd

# Dependencies
minecraft_version=26.1
minecraft_version_range=[26.1,26.2)

neoforge_version=26.1.0.8-beta
neoforge_version_range=[26.1,27.0)

fabric_loader_version=0.18.4
fabric_api_version=0.144.0+26.1

cloth_config_version=26.1.154
cloth_config_version_range=[26.1,)

kubejs_version=2101.7.2-build.321
rhino_version=2101.2.7-build.81
ipc_version=0.5.2
