org.gradle.jvmargs=-Xmx3G

minecraft_version=1.21.10
minecraft_version_sem_range=>=1.21.9
minecraft_version_mav_range=[1.21.9,1.21.11)

enabled_platforms=fabric,neoforge

archives_base_name=SimpleDiscordRichPresence
mod_version=97.0.0
maven_group=com.sunekaer.mods

curseforge_id=334853
modrinth_id=SCAopByd
maven_url=https://maven.nanite.dev/

architectury_version=18.0.8
architectury_version_sem_range=>=18.0.0
architectury_version_mav_range=[18.0.0,)

fabric_loader_version=0.18.4
fabric_api_version=0.138.4+1.21.10

neoforge_version=21.10.64
neoforge_version_range=[21.9.0,21.11.0)

cloth_config_version=20.0.149
cloth_config_version_sem_range=>=20.0.0
cloth_config_version_mav_range=[20.0.0,)

kubejs_version=2101.7.2-build.321
rhino_version=2101.2.7-build.81
ipc_version=0.5.1
