org.gradle.jvmargs=-Xmx3G

mod_id=sdrp
archives_base_name=SimpleDiscordRichPresence
maven_group=com.sunekaer.mods

mod_version=1

# Dependencies
minecraft_version=26.2
minecraft_version_range_maven=[26.2,26.3)
minecraft_version_range_semver=>=26.2
supported_minecraft_versions=26.2

neoforge_version=26.2.0.6-beta
neoforge_version_range=[26.2,27.0)

fabric_loader_version=0.19.3
fabric_api_version=0.152.2+26.2
fabric_api_version_range=>=0.152.2+26.2

nanite_library_version=26.2.0.1
nanite_library_version_maven=[26.2.0.1,)
nanite_library_version_semver=>=26.2.0.1

ipc_version=0.5.2

curseforge_id=334853
modrinth_id=SCAopByd
