plugins {
    id 'net.fabricmc.fabric-loom'
}

loom {
    // accessWidenerPath = file("src/main/resources/sdrp.accesswidener")
}

repositories {
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    implementation 'com.google.code.findbugs:jsr305:3.0.2'

    compileOnly("dev.nanite.forks:discord-ipc:${ipc_version}")

    compileOnly("me.shedaniel.cloth:cloth-config:${project.cloth_config_version}")

    // Unit testing
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}
