modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL="https://github.com/Sunekaer/Simple-Discord-Rich-Presence/issues"
license="All Rights Reserved"

[[mods]]
modId="sdrp"
displayTest="IGNORE_ALL_VERSION"
version="${version}"
displayName="Simple Discord Rich Presence"
displayURL="https://www.curseforge.com/minecraft/mc-mods/simple-discord-rich-presence"
logoFile="logo.png"
authors="Sunekaer"
description='''
Simple Discord Rich Presence
'''

[[dependencies.sdrp]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sdrp]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sdrp]]
modId = "architectury"
type = "required"
versionRange = "[13.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.sdrp]]
modId = "cloth_config"
type = "required"
versionRange = "[15.0.127,)"
ordering = "NONE"
side = "BOTH"
