plugins {
    id 'net.neoforged.moddev'
}

neoForge {
    version = project.neoforge_version
    // accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        configureEach {
            logLevel = org.slf4j.event.Level.DEBUG
        }

        client {
            client()
        }

        server {
            server()
            programArgument '--nogui'
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
            sourceSet(project(":common").sourceSets.main)
        }
    }
}

repositories {
    maven {
        url = "https://cursemaven.com/"
        content {
            includeGroup "curse.maven"
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation("me.shedaniel.cloth:cloth-config-neoforge:${rootProject.cloth_config_version}")

    runtimeOnly "dev.nanite.forks:discord-ipc:${ipc_version}"
    implementation "dev.nanite.forks:discord-ipc:${ipc_version}"

    // This was painful.
    // modCompileOnly("dev.latvian.mods:kubejs-neoforge:$kubejs_version") {
    //     exclude group: "dev.latvian.apps", module: "tiny-java-server"
    // }
}

java {
    withSourcesJar()
}