plugins {
    id 'net.neoforged.moddev'
}

neoForge {
    version = project.neoforge_version
    // accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        configureEach {
            logLevel = org.slf4j.event.Level.DEBUG
        }

        client {
            client()
        }

        server {
            server()
            programArgument '--nogui'
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
            sourceSet(project(":common").sourceSets.main)
        }
    }
}

repositories {
    maven {
        url = "https://cursemaven.com/"
        content {
            includeGroup "curse.maven"
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    api("dev.nanite.mods:nanite-library-neoforge:${nanite_library_version}")
    jarJar(api("dev.nanite.forks:discord-ipc:${ipc_version}"))
}

java {
    withSourcesJar()
}
